name: 빌드 및 배포 

on:
  push:
    branches: [ main ]

env:
  USERNAME: moon8sun 

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: 원격저장소에서 소스를 복사
        uses: actions/checkout@v3

      - name: 소스 파일을 docker이미지로 빌드한다
        run: |
          cd backend
          docker build -t ${{ env.USERNAME }}/backend:latest .
          cd ..

      - name: docker hub에 로그인 한다. 
        run: docker login -u ${{ env.USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: 생성된 이미지를 docker hub에 푸시한다
        run: docker push ${{ env.USERNAME }}/backend:latest
        
      - name: 개인키 인증서 파일 생성
        run: |
          mkdir -p ~/.ssh
          echo ${{ secrets.SSH_KEY }} > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t ed25519 >> ~/.ssh/known_host
          scp ../frontend/index.html ubuntu@3.34.194.189:~/step3/frontend
  deploy:
    needs: build-docker-image
    name: deploy
    runs-on: [ self-hosted, label-kosa2 ]
    steps:

      - name: docker hub에 로그인 한다. 
        run: docker login -u ${{ env.USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: 서비스 실행
        run: |
          cd /home/ubuntu/step3
          #echo '운영서버에서 github에 파일 복사해 옴'
          #git clone https://github.com/leemis825/docker-project.git
          #cd docker-project/frontend/index.html frontend
          #rm -rf docker-project
          docker compose up -d